// import "@/app/icons.js";
import { Geist, Geist_Mono } from "next/font/google";
import { Menu } from "./components/Menu";
import "./globals.css";
import "@/styles/menu.css";
import "@/styles/rules.css";
import "@/styles/banner.css";
import "@/styles/checkboxes.css";
import "@/styles/daily.css";
import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Menu content={children} />
      </body>
    </html>
  );
}
